add_newline = true

[character]
success_symbol = "[ğ›Œ](bold green)"
error_symbol = "[ğ›Œ](bold red)"

[rust]
symbol = " î¨ "

[git_branch]
symbol = " î‚  "

[package]
symbol = " ï£– "

[python]
symbol = " ï Ÿ "

[lua]
symbol = " î˜  "

